name: Developer's PR Check Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  changes:
    name: "Detect Directory Changes"
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.detect.outputs.changed }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Get commit hash
        id: hash
        run: |
          git checkout ${{ steps.branch-names.outputs.current_branch }}
          hash=$(git log -n 1 --pretty=format:"%H")
          echo $hash
          echo "hash=$hash" >> $GITHUB_OUTPUT 

      - name: Find Changed Directories
        id: detect
        run: |
          changed_dirs=$(git diff-tree --no-commit-id --name-only -r ${{ steps.hash.outputs.hash }} | \
          grep -vE '^(.github|\.idea|boot|gradle)/' | cut -d'/' -f1 | uniq | \
          awk 'BEGIN { printf("[\n") } { if (NR > 1) printf(",\n"); printf("  {\n    \"module\": \"%s\"\n  }", $0) } END { printf("\n]\n") }')
          
          echo "changed=$(jq -r -c . <<< "$changed_dirs")" >> $GITHUB_OUTPUT 

      - run: echo ${{ steps.detect.outputs.changed }}

  deploy:
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      matrix: 
        include: ${{ fromJSON(needs.changes.outputs.changed) }}
      fail-fast: false
      max-parallel: 1

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract target branch name
        id: branch
        run: |
          echo "branch=${{ github.event.pull_request.base.ref }}" >> $GITHUB_OUTPUT

      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v8

      - run: git pull && git merge origin/${{ steps.branch.outputs.branch }} develop

      - name: Update Image Version
        run: |
          echo "teste-${{ steps.branch.outputs.branch }}" >> ./${{ matrix.module }}/test.txt

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}