name: Developer's PR Check Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  changes:
    name: "Detect Directory Changes"
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.set-matrix.outputs.matrix }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Get latest commit SHA
        id: extract_sha
        shell: bash
        run: |
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          commit_sha=$(git ls-remote origin "refs/heads/$branch" | cut -f1)
          echo "commit_sha=$commit_sha" >> $GITHUB_OUTPUT

      - name: Find Changed Directories
        id: detect
        run: |
          changed_dirs=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.before }} ${{ steps.extract_sha.outputs.commit_sha }} | \
          grep -vE '^(.github|\.idea|boot|gradle)/' | cut -d'/' -f1 | uniq | awk '{ printf("\"%s\",", $0) }' | sed 's/, $//')
          
          echo "changed=$changed_dirs" >> $GITHUB_OUTPUT 

      - name: Generate JSON Output
        id: json
        run: |
          cd ./.github/workflows

          echo "[" >> ./matrix_includes.json
          echo "  {" >> ./matrix_includes.json

          echo "    \"module\":[${{ steps.detect.outputs.changed }}]" >> ./matrix_includes.json

          echo "  }" >> ./matrix_includes.json

          echo "]" >> ./matrix_includes.json


          cat ./matrix_includes.json

      - id: set-matrix
        uses: JoshuaTheMiller/conditional-build-matrix@main

      - run: echo ${{ steps.set-matrix.outputs.matrix }}

  build:
    name: Build and Analyze
    runs-on: self-hosted
    needs: changes
    strategy:
      matrix: ${{ fromJSON(needs.test.outputs.changed) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: echo ${{ fromJSON(needs.test.outputs.changed) }}